mygamelist/games/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

app_name = 'games'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('global/', views.GlobalIndexView, name='gindex'),
    path('genre/<int:genre_id>/', views.GenreView, name='genre'),
    path('genre/<int:genre_id>/<str:name>/', views.GenreView, name='genre'),
    path('tag/<int:tag_id>/', views.GamesTaggedWithView, name='tag'),
    path('tag/<int:tag_id>/<str:name>/', views.GamesTaggedWithView, name='tag'),
    path('collection/<int:col_id>/', views.GamesInCollectionView, name='collection'),
    path('collection/<int:col_id>/<str:name>/', views.GamesInCollectionView, name='collection'),
    path('customlist/<int:list_id>/', views.GamesInCustomListView, name='customlist'),
    path('platform/<int:pk>/', views.PlatformView.as_view(), name='platform'),
    path('platform/<int:pk>/<str:name>/', views.PlatformView.as_view(), name='platform'),
    path('game/<int:game_id>/', views.GameView, name='game'),
    path('game/<int:game_id>/<str:name>/', views.GameView, name='game'),
    path('game/<int:game_id>/<str:name>/<str:tab>/', views.GameView, name='game'),
    path('user/<int:user_id>/', views.ProfileView, name='profile'),
    path('user/<int:user_id>/<str:name>/', views.ProfileView, name='profile'),
    path('user/<int:user_id>/<str:name>/<str:tab>/', views.ProfileView, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='games/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('gamelist/', views.GameListView, name='gamelist'),
    path('gamelist/random', views.GameListRandomView, name='gamelistrandom'),
    path('gamelist/export', views.GameListExportView, name='gamelistexport'),
    path('gamelist/<str:edit_type>', views.GameListView, name='gamelist'),
    path('gamelist/<str:edit_type>/<int:entry_id>', views.GameListView, name='gamelist'),
    path('browse/', views.BrowseView, name='browse'),
    path('browse/collection/', views.BrowseCollectionView, name='browsecollection'),
    path('browse/users/', views.BrowseUserView, name='browseusers'),
    path('better/', views.BetterView, name='better'),
    path('better/<str:better_type>/', views.BetterView, name='better'),
    path('notifications/', views.NotificationsView, name='notifications'),
    path('notifications/<str:action>/', views.NotificationsView, name='notifications'),
    path('recommendations/', views.RecommendationsView, name='recommendations'),
    path('recommendations/view/<int:user_id>', views.RecommendationsView, name='recommendations'),
    path('recommendations/refresh/', views.RecommendationsRefreshView, name='recrefresh'),
    path('game/ignore/<int:game_id>/', views.IgnoreGameView, name='ignore'),
    path('game/addtag/<int:game_id>/', views.TagAdditionRequestView, name='tagreq'),
    path('game/rateaspect/', views.RateAspectView, name='rateaspect'),
    path('user/follow/<int:user_id>/', views.FollowUserView, name='follow'),
    path('status/like/', views.LikeStatusView, name='likestatus'),
    path('status/like/<int:status_id>/', views.LikeStatusView, name='likestatus'),
    path('status/delete/<int:status_id>/', views.DeleteStatusView, name='deletestatus'),
    path('settings/', views.SettingsView, name='settings'),
    path('settings/avatar/', views.ChangeAvatarView, name='changeavatar'),
    path('settings/ignoredtags/', views.ChangeIgnoredTagsView, name='changeignoredtags'),
    path('settings/customlists/', views.ChangeCustomListsView, name='changecustomlists'),
    path('settings/customlists/add', views.AddCustomListView, name='addcustomlist'),
    path('settings/customlists/delete/<int:list_id>/', views.DeleteCustomListView, name='deletecustomlist'),
    path('settings/customlists/edit/<int:list_id>/', views.EditCustomListView, name='editcustomlist'),
    path('settings/platforms/', views.HidePlatformsView, name='hideplatforms'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mygamelist/games/models.py
from django.db import models
from decimal import Decimal
from uuid import uuid4
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

def random_cover_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return 'covers/' + filename

def random_banner_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return 'banners/' + filename

def random_background_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return 'backgrounds/' + filename

def random_screen_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return 'screenshots/' + filename

def random_avatar_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    return 'avatars/' + filename

class Platform(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    shorthand = models.CharField(max_length=50, blank=True, default='')
    default = models.BooleanField(default=False, null=False)

    class Meta:
        ordering = ['category', 'name']

    def __str__(self):
        return self.category + " - " + self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=250, blank=True)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Game(models.Model):
    name = models.CharField(max_length=150)
    year = models.IntegerField()
    trailer_link = models.URLField(max_length=250, blank=True, default='')
    image = models.ImageField(upload_to=random_cover_filename, null=True)
    background = models.ImageField(upload_to=random_background_filename, null=True, blank=True)
    screen1 = models.ImageField(upload_to=random_screen_filename, null=True, blank=True)
    screen2 = models.ImageField(upload_to=random_screen_filename, null=True, blank=True)
    screen3 = models.ImageField(upload_to=random_screen_filename, null=True, blank=True)
    screen4 = models.ImageField(upload_to=random_screen_filename, null=True, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    description = models.TextField(blank=True, default='')
    aliases = models.TextField(blank=True, default='')
    main_link = models.URLField(max_length=250, blank=True, default='', verbose_name="Main Website")
    wikipedia_link = models.URLField(max_length=250, blank=True, default='', verbose_name="Wikipedia")
    gamefaqs_link = models.URLField(max_length=250, blank=True, default='', verbose_name="GameFAQs Link")
    steam_link = models.URLField(max_length=250, blank=True, default='', verbose_name="Steam Link")
    howlongtobeat_link = models.URLField(max_length=250, blank=True, default='', verbose_name="HowLongToBeat Link")
    pcgamingwiki_link = models.URLField(max_length=250, blank=True, default='', verbose_name="PCGamingWiki Link")
    winehq_link = models.URLField(max_length=250, blank=True, default='', verbose_name="WineHQ Link")
    mobygames_link = models.URLField(max_length=250, blank=True, default='', verbose_name="MobyGames Link")
    vndb_link = models.URLField(max_length=250, blank=True, default='', verbose_name="VNDB Link")
    temp_pop_score = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return self.name + " (" + str(self.year) + ")"

@receiver(post_save, sender=User)
def create_userprofile_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        sexual_content = Tag.objects.get(name="Sexual Content")
        instance.userprofile.banned_tags.add(sexual_content)
        common_platforms = Platform.objects.filter(default=True)
        instance.userprofile.enabled_platforms.set(common_platforms)
        instance.userprofile.save()

class UserGameListEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    platform = models.ForeignKey(Platform, blank=True, null=True, on_delete=models.CASCADE)
    statuses = [
        ("PLAN", "Plan to Play"),
        ("PLAY", "Playing"),
        ("CMPL", "Completed"),
        ("DROP", "Dropped"),
        ("HOLD", "Paused"),
        ("IMPT", "Imported")
    ]
    status = models.CharField(max_length=4, choices=statuses, default="PLAN")
    score = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    hours = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    comments = models.CharField(max_length=500, blank=True, default='')
    start_date = models.DateField(blank=True, null=True)
    stop_date = models.DateField(blank=True, null=True)
    times_replayed = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + " - " + self.game.name

class GameVerifiedPlatform(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    platform = models.ForeignKey(Platform, on_delete=models.CASCADE)
    year = models.IntegerField(default=0)
    retroachievements_id = models.IntegerField(blank=True, null=True)
    mobygames_link = models.URLField(max_length=250, blank=True, default='', verbose_name="MobyGames Link")

    def __str__(self):
        return self.game.name + " - " + self.platform.name

class UserGameAspectRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    difficulty = models.IntegerField(default=0)
    replayability = models.IntegerField(default=0)
    graphics = models.IntegerField(default=0)
    audio = models.IntegerField(default=0)
    story = models.IntegerField(default=0)
    recommendability = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + " - " + self.game.name

class ManualUserGameListEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    platform = models.ForeignKey(Platform, blank=True, null=True, on_delete=models.CASCADE)
    statuses = [
        ("PLAY", "Playing"),
        ("CMPL", "Completed"),
        ("DROP", "Dropped"),
        ("HOLD", "Paused"),
        ("PLAN", "Plan to Play"),
        ("IMPT", "Imported")
    ]
    status = models.CharField(max_length=4, choices=statuses, default="PLAN")
    score = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    hours = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    comments = models.CharField(max_length=500, blank=True, default='')
    start_date = models.DateField(blank=True, null=True)
    stop_date = models.DateField(blank=True, null=True)
    times_replayed = models.IntegerField(default=0)
    never_migrate = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.user.username + " - " + self.name

class UserGameStatus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    statuses = [
        ("PLAY", "Playing"),
        ("CMPL", "Completed"),
        ("DROP", "Dropped"),
        ("HOLD", "Paused"),
        ("PLAN", "Plan to Play"),
        ("LOGD", "Logged")
    ]
    status = models.CharField(max_length=4, choices=statuses)
    created_at = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField(User, blank=True, related_name='usergamestatus_liked_by')
    data = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return self.user.username + " " + self.status + " " + self.game.name

class Notification(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notif_type = models.CharField(max_length=10)
    notif_object_id = models.IntegerField()

class Recommendation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slot = models.IntegerField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    rec_data = models.CharField(max_length=10)

class CollectionType(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

class Collection(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(CollectionType, on_delete=models.CASCADE)
    description = models.TextField(blank=True, default='')
    games = models.ManyToManyField(Game, blank=True)

    def __str__(self):
        return self.category.name + " - " + self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=random_avatar_filename, default='avatars/default.png')
    contribution_score = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    banned_tags = models.ManyToManyField(Tag, blank=True)
    ignored_games = models.ManyToManyField(Game, blank=True)
    ignored_collections = models.ManyToManyField(Collection, blank=True)
    enabled_platforms = models.ManyToManyField(Platform, blank=True)
    followed_users = models.ManyToManyField(User, blank=True, related_name='userprofile_followed_users')

class UserSettings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating_systems = [

mygamelist/games/forms.py
import magic
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ManualUserGameListEntry, UserGameListEntry, Platform, UserProfile, Tag, TagAdditionRequest, CustomList

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
            self.fields['username'].widget.attrs.update({'placeholder': 'Username'})
            self.fields['password1'].widget.attrs.update({'placeholder': 'Password'})
            self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password'})

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', )

class ManualGameForm(forms.ModelForm):
    class Meta:
        model = ManualUserGameListEntry
        fields = ['name', 'platform', 'status', 'score', 'hours', 'comments', 'start_date', 'stop_date', 'times_replayed']
        
        widgets = {
            'start_date': forms.DateInput(format='%Y-%m-%d'),
            'stop_date': forms.DateInput(format='%Y-%m-%d')
        }

class GameEntryForm(forms.ModelForm):
    class Meta:
        model = UserGameListEntry
        fields = ['platform', 'status', 'score', 'hours', 'comments', 'start_date', 'stop_date', 'times_replayed']
        
        widgets = {
            'start_date': forms.DateInput(format='%Y-%m-%d'),
            'stop_date': forms.DateInput(format='%Y-%m-%d')
        }

class ChangeAvatarForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        main, sub = magic.from_buffer(avatar.read(), mime=True).split('/')
        if not (main == 'image' and sub in ['jpeg', 'gif', 'png']):
            raise forms.ValidationError(u'Please use a JPEG, GIF or PNG image.')

        if len(avatar) > (512 * 1024):
            raise forms.ValidationError(u'Avatar file size may not exceed 512KB.')

        return avatar

class ChangeIgnoredTagsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['banned_tags']
    banned_tags = forms.ModelMultipleChoiceField(
            queryset=Tag.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=False
        )

class HidePlatformsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['enabled_platforms']
    enabled_platforms = forms.ModelMultipleChoiceField(
            queryset=Platform.objects.all(),
            widget=forms.CheckboxSelectMultiple,
            required=False
        )

class TagAdditionRequestForm(forms.ModelForm):
	class Meta:
		model = TagAdditionRequest
		fields = ['tag', 'comments']

class CustomListForm(forms.ModelForm):
	class Meta:
		model = CustomList
		fields = ['name', 'privacy_level']

mygamelist/games/templates/games/add_manual_game.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}My Games :: Remember.Games{% endblock %}

{% block embedpreview %}
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="My Games :: Remember Games" />
	<meta name="twitter:description" content="Remember Games is a website you can use to track games you've played." />
	<meta name="twitter:image" content="" />
{% endblock %}

{% block navitems %}
	<li class="nav-item">
	<a class="nav-link" href="/">Home</a>
	</li>
	<li class="nav-item">
	<a class="nav-link active" href="{% url 'games:gamelist' %}">My Games</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="{% url 'games:browse' %}">Browse</a>
	</li>
{% endblock %}

{% block content %}
<div class="container">
    <br>{{ form.errors }}
    <div class="text-white bg-dark mb-3 rounded" style="max-width: 100%">
    <br>
    <form action="{% url 'games:gamelist' 'add-manual' %}" method="post" autocomplete="off">
        <div class="row">
            {% csrf_token %}
            <br>
            <div class="col-4" align="center">
                <label for="id_name"><b>Game Name:</b></label><br>
                <input type="text" name="name" maxlength="150" required="" value="{{ form.name.value|default_if_none:"" }}" id="id_name"><br>
                <br>
                <label for="id_score">Score:</label><br>
                {% if settings.score_type == 'SMIL' %}
                <link href="{% static 'css/smile.css' %}" rel="stylesheet">
                <input type="radio" name="score" value="7.5" class="happy" {% if form.score.value >= 7.0 %}checked{% endif %}>
                <input type="radio" name="score" value="5.0" class="neutral" {% if form.score.value < 7.0 and form.score.value >= 5.0 %}checked{% endif %}>
                <input type="radio" name="score" value="2.5" class="sad" {% if form.score.value < 5.0 %}checked{% endif %}>
                <input type="radio" name="score" value="" class="none" {% if not form.score.value %}checked{% endif %}><br>
                {% else %}
                <input type="number" name="score" step="0.01" value="{{ form.score.value|default_if_none:"" }}" id="id_score"><br>
                {% endif %}
                <br>
                <label for="id_hours">Hours:</label><br>
                <input type="number" name="hours" step="0.01" value="{{ form.hours.value|default_if_none:"" }}" id="id_hours"><br>
            </div>
            <div class="col-4" align="center">
                <label for="id_platform"><b>Platform:</b></label><br>
                <select name="platform">
                    <option value="">---------</option>
                    {% for platform in dropdown_platforms %}
                        <option value="{{ platform.id }}"{% if platform.id|slugify == form.platform.value|slugify %} selected{% endif %}>{{ platform.category }} - {{ platform.name }}</option>
                    {% endfor %}
                </select><br>
                <br>
                <label for="id_start_date">Start Date:</label><br>
                <input type="text" name="start_date" id="id_start_date" value="{{ form.start_date.value|default_if_none:"" }}" placeholder="YYYY-MM-DD"><br>
                <br>
                <label for="id_times_replayed">Times Replayed:</label><br>
                <input type="number" name="times_replayed" required="" value="{{ form.times_replayed.value }}" id="id_times_replayed"><br>
            </div>
            <div class="col-4" align="center">
                <label for="id_status"><b>Status:</b></label><br>
                <select name="status" id="id_status">
                    <option value="PLAN"{% if form.status.value == 'PLAN' %} selected=""{% endif %}>Plan to Play</option>
                    <option value="PLAY"{% if form.status.value == 'PLAY' %} selected=""{% endif %}>Playing</option>
                    <option value="CMPL"{% if form.status.value == 'CMPL' %} selected=""{% endif %}>Completed</option>
                    <option value="DROP"{% if form.status.value == 'DROP' %} selected=""{% endif %}>Dropped</option>
                    <option value="HOLD"{% if form.status.value == 'HOLD' %} selected=""{% endif %}>Paused</option>
                </select><br>
                <br>
                <label for="id_stop_date">Stop Date:</label><br>
                <input type="text" name="stop_date" id="id_stop_date" value="{{ form.stop_date.value|default_if_none:"" }}" placeholder="YYYY-MM-DD"><br>
                <br>
                <label for="id_comments">Comments:</label><br>
                <input type="text" name="comments" maxlength="500" value="{{ form.comments.value|default_if_none:"" }}" id="id_comments"><br>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-4" align="center">
            </div>
            <div class="col-4" align="center"></div>
            <div class="col-4" align="center">
                <button class="btn btn-primary" type="submit">Add</button><br>
            </div>
            <input type="hidden" name="next" value="{{ next }}">
        </div>
        </form>
        <br><br>
    </div>
    <div class="row">
        <div class="col-12" align="center">
            {% if settings.score_type != 'SMIL' and settings.score_type != 'STAR' %}<br>
            Scoring Guide:<br>
            10 = Masterpiece, 9 = Great, 8 = Very Good, 7 = Good, 6 = Fine, 5 = Average, 4 = Bad, 3 = Very Bad, 2 = Horrible, 1 = Appalling<br>{% endif %}
        </div>
    </div>
</div>
<br><br>
{% endblock %}

mygamelist/games/templates/games/tag_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}{{ tag.name }} :: Remember Games{% endblock %}

{% block embedpreview %}
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="{{ tag.name }} :: Remember Games" />
	<meta name="twitter:description" content="Remember Games is a website you can use to track games you've played." />
	<meta name="twitter:image" content="" />
{% endblock %}

{% block navitems %}
	<li class="nav-item">
	<a class="nav-link" href="/">Home</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="{% url 'games:gamelist' %}">My Games</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="{% url 'games:browse' %}">Browse</a>
	</li>
{% endblock %}

{% block content %}
<div class="container-fluid">
	<center><h3>Games tagged with "{{ tag.name }}":</h3></center>
	<div class="row">
		{% for game in game_list %}
			{% if game.image %}
			<div class="col d-flex align-items-md-center justify-content-md-center">
			{% firstof game.name|slugify '_' as gameslug %}
			<a href="{% url 'games:game' game.id gameslug %}"><img class="rounded mx-auto d-block" style="object-fit:contain;max-height:250px;max-width:167px;" src="{{ game.image.url }}"></a>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	<div class="col-md-12" align="center">
		{% if game_list.has_previous %}
		<a href="?page={{ game_list.previous_page_number }}">&laquo;</a>
		{% else %}
		&laquo;
		{% endif %}
		{{ game_list.number }}
		{% if game_list.has_next %}
		<a href="?page={{ game_list.next_page_number }}">&raquo;</a>
		{% else %}
		&raquo;
		{% endif %}
	</div>
</div>
{% endblock %}

mygamelist/games/templates/games/user_list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}My Games :: Remember Games{% endblock %}

{% block embedpreview %}
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="My Games :: Remember Games" />
	<meta name="twitter:description" content="Remember Games is a website you can use to track games you've played." />
	<meta name="twitter:image" content="" />
{% endblock %}

{% block navitems %}
	<li class="nav-item">
	<a class="nav-link" href="/">Home</a>
	</li>
	<li class="nav-item">
	<a class="nav-link active" href="{% url 'games:gamelist' %}">My Games</a>
	</li>
	<li class="nav-item">
	<a class="nav-link" href="{% url 'games:browse' %}">Browse</a>
	</li>
{% endblock %}

{% block content %}
<div class="container">
	<br>
	<center><a href="{% url 'games:gamelist' 'add-manual' %}" class="gamelink">Add Game Manually</a> | <a href="{% url 'games:gamelistexport' %}" class="gamelink">Export List</a> | <a href="{% url 'games:gamelistrandom' %}" class="gamelink">Random Plan to Play</a> | <a href="{% url 'games:recommendations' %}" class="gamelink">Recommendations</a></center><br>
	<div class="row">
		{% for status, game_list in total_list.items %}
			<table class="table table-hover table-striped table-dark" style="text-align: center;">
			<tr><td colspan="6"><h3><center>{{ status }}</center></h3></td></tr>
			<tr>
			<th scope="col" width="5%">Actions</th>
			<th scope="col" width="45%"><a href="{% url 'games:gamelist' %}" style="color: white">Game Title</a></th>
			<th scope="col" width="15%"><a href="{% url 'games:gamelist' %}?sort=platform" style="color: white">Platform</a></th>
			<th scope="col" width="10%"><a href="{% url 'games:gamelist' %}?sort=score" style="color: white">Score</a></th>
			<th scope="col" width="10%"><a href="{% url 'games:gamelist' %}?sort=hours" style="color: white">Hours</a></th>
			<th scope="col" width="15%">Flags</th>
			</tr>
				{% for entry_name, entry in game_list.items %}
				<tr>
					<td>
						<a href="{% url 'games:gamelist' entry.edit_type entry.id %}?next=/gamelist">&#x2699;</a>
						<a href="{% url 'games:gamelist' entry.delete_type entry.id %}">&#x1F5D1;</a>
					</td>
					<td>{% if entry.game_id %}<a class="gamelink" href="{% url 'games:game' entry.game_id entry.name|slugify %}">{% endif %}{{ entry.name }}{% if entry.game_id %}</a>{% endif %}</td>
					<td>{% if entry.platform %}{% if entry.platform.shorthand %}{{ entry.platform.shorthand }}{% else %}{{ entry.platform.name }}{% endif %}{% else %}None{% endif %}</td>
					<td>{% if settings.score_type == 'SMIL' %}
							{% if entry.score >= 7.0 %}
								<img src="{% static 'icons/happy.svg' %}" style="max-height:25px;">
							{% elif entry.score < 7.0 and entry.score >= 5.0 %}
								<img src="{% static 'icons/neutral.svg' %}" style="max-height:25px;">
							{% elif entry.score < 5.0 %}
								<img src="{% static 'icons/sad.svg' %}" style="max-height:25px;">
							{% else %}
								<img src="{% static 'icons/circle.svg' %}" style="max-height:25px;">
							{% endif %}
						{% else %}
							{{ entry.score }}
						{% endif %}</td>
					<td>{{ entry.hours }}</td>
					<td>
						{% if entry.comments %}<span title="{{ entry.comments }}">&#x1F4AC;</span>{% endif %}
						{% if entry.times_replayed > 0 %}<span title="Replayed {{ entry.times_replayed }} time{% if entry.times_replayed > 1 %}s{% endif %}!">&#x1F501;</span>{% endif %}
						{% if entry.never_migrate %}<span title="This has been flagged by a moderator as an entry that will never be automatically migrated.">&#x26A0;</span>{% endif %}
					</td>
				</tr>
				{% endfor %}
			</table>
		{% endfor %}
	</div>
</div>
{% endblock %}